force-app/main/default/objects/Simploud__Controlled_Document__c/Simploud__Controlled_Document__c.object-meta.xml
<CustomObject>
    <label>Controlled Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controlled Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Simploud__Controlled_Document__c/fields/Google_Docs_URL__c.field-meta.xml
<CustomField>
    <fullName>Google_Docs_URL__c</fullName>
    <label>Google Docs URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GoogleEditorController.cls
public with sharing class GoogleEditorController {

    @AuraEnabled
    public static string getEditorUrl(String recordId) {
        Simploud__Controlled_Document__c doc = [SELECT Id, Google_Docs_URL__c FROM Simploud__Controlled_Document__c WHERE Id = :recordId];

        return doc.Google_Docs_URL__c;
    }

    @AuraEnabled
    public static void saveDocument(String recordId) {
        GoogleDocsApiHandler.saveDocument(new Id[] { Id.valueOf(recordId) });
    }

    @AuraEnabled
    public static string getDownloadLink(String recordId) {
        Simploud__Controlled_Document__c doc = [SELECT Id, Google_Docs_URL__c, (SELECT Id, ContentDocumentId FROM ContentDocumentLinks) FROM Simploud__Controlled_Document__c WHERE Id = :recordId];

        ContentDocument cd = [SELECT Id, FileExtension FROM ContentDocument WHERE Id = :doc.ContentDocumentLinks[0].ContentDocumentId];

        return doc.Google_Docs_URL__c + '/export?format=' + cd.FileExtension;
    }
}